# Generated by Django 3.1 on 2022-03-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bopinfomodel_menberinfomodel_personalcategorymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bopinfomodel',
            name='cash_out',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bopinfomodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bopinfomodel',
            name='memo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bopinfomodel',
            name='number_of_hands',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bopinfomodel',
            name='user_id',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='itemcategorymodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menberinfomodel',
            name='user_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personalcategorymodel',
            name='category_id',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='personalcategorymodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personalcategorymodel',
            name='user_id',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='personalratemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personalratemodel',
            name='rate_id',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='personalratemodel',
            name='user_id',
            field=models.CharField(max_length=11),
        ),
    ]
